review dz1
siberiacalling/c_homeworks pull request #1
Opened 2019-03-10 10:28 UTC by siberiacalling

2019-03-10 10:30 UTC, siberiacalling commented
@o2gy84

2019-03-10 10:38 UTC, siberiacalling commented
@o2gy84

2019-03-11 10:47 UTC, o2gy84 requested changes

2019-03-11 10:47 UTC, o2gy84 commented on dz_1.c
> +    strings = realloc(strings, (strings_capacity) * sizeof(*strings));
нельзя реаллочить память саму в себя. в случае ошибки realloc вернет NULL, после чего указатель на strings "теряется", и память, выделенная под этот указатель - утекает.

2019-03-11 10:47 UTC, o2gy84 commented on dz_1.c
> +            strings = realloc_memory(strings, strings_capacity);
не видно проверки ошибок, хотя realloc_memory может возвращать ошибку

2019-03-11 10:49 UTC, o2gy84 commented
мне кажется, у меня к этому репозиторию только read only доступ.
я ничего не могу сделать с открытым пулл-реквестом

2019-03-11 14:59 UTC, siberiacalling commented on dz_1.c
> +            strings = realloc_memory(strings, strings_capacity);
@o2gy84 исправила замечания

2019-03-12 11:28 UTC, closed without merging